### PR TITLE
Proper fix for the formatArgument function in Redisent

### PR DESCRIPTION
**Pull request by mfauveau**

### CODE REVIEW

**Comment by ernestova** [comment]
Any news on this pull request ?  @kamisama are you considering to accept it as I am having the current issue too.

**Comment by kamisama** [comment]
I'm still waiting for @mfauveau for additional explanations about the PR.

The new code is not returning the same length as the previous implementation, because it's imploding with the whitespace char.

**Comment by mfauveau** [comment]
@kamisama in my tests my change doesn't create any specific issue. The len is calculated based on the new $arg.

**Comment by kamisama** [comment]
I didn't notice that you modified the `$arg` variable too.

**Pull request merged**
